pandas 

> pandas is a powerfull python library for manupulation and analysis of data

> Its a open source library 

> fast(built on top of numpy), flexible(different resource),productive library

#### install

In [225]:
 pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [226]:
import pandas as pd

In [227]:
print(pd.__version__)

2.2.3

#### series  - one dimensional rray (data structure)with labal

In [228]:
l1 = [1,2,3,4,5]
type(l1)

list

In [229]:
 pd.Series(l1)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [230]:
 pd.Series(l1,name = "Series")

0    1
1    2
2    3
3    4
4    5
Name: Series, dtype: int64

In [231]:
s = pd.Series(l1, index = ["apple","banana","cherry","elderberry","data"],name = "my series")

In [232]:
s

apple         1
banana        2
cherry        3
elderberry    4
data          5
Name: my series, dtype: int64

In [233]:
s = pd.Series(l1, index = ["a","b","c","d","e"],name = "my series")

In [234]:
s

a    1
b    2
c    3
d    4
e    5
Name: my series, dtype: int64

In [235]:
s['a']

np.int64(1)

In [236]:
type(s)

pandas.core.series.Series

>Note:Index in series are immutable(cant change)

In [237]:
s.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [238]:
s.values

array([1, 2, 3, 4, 5])

In [239]:
# Changing the index of a pandas series

s.rename(index = {'b':'y'},inplace = True)

In [240]:
s

a    1
y    2
c    3
d    4
e    5
Name: my series, dtype: int64

### dataframe - Its a sd array(just like tables)

row and column

In [241]:
dict1 = {'name':['virat','rohit','Dhoni','jadega','bumrah'],
        'age':[34,33,40,32,30],
        'Marks':[85,90,75,80,70],
        'Role':['batsman','batsman','wicket keeper','all rounder','bowler']}


pd.DataFrame(dict1)

     name  age  Marks           Role
0   virat   34     85        batsman
1   rohit   33     90        batsman
2   Dhoni   40     75  wicket keeper
3  jadega   32     80    all rounder
4  bumrah   30     70         bowler

In [242]:
df.tail(3)

NameError: name 'df' is not defined

In [ ]:
df=pd.DataFrame(dict1)

In [ ]:
df.head()

     name  age  Marks           Role
0   virat   34     85        batsman
1   rohit   33     90        batsman
2   Dhoni   40     75  wicket keeper
3  jadega   32     80    all rounder
4  bumrah   30     70         bowler

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
len(df)

5

In [ ]:
df.count()

name     5
age      5
Marks    5
Role     5
dtype: int64

In [ ]:
df

     name  age  Marks           Role
0   virat   34     85        batsman
1   rohit   33     90        batsman
2   Dhoni   40     75  wicket keeper
3  jadega   32     80    all rounder
4  bumrah   30     70         bowler

In [ ]:
df.columns

Index(['name', 'age', 'Marks', 'Role'], dtype='object')

In [ ]:
df['name']

0     virat
1     rohit
2     Dhoni
3    jadega
4    bumrah
Name: name, dtype: object

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
type(df['name'])

pandas.core.series.Series

In [ ]:
df['name'].value_counts()

name
virat     1
rohit     1
Dhoni     1
jadega    1
bumrah    1
Name: count, dtype: int64

#### Basic operation


> Importing data set from different files


>Importing tabular dataset

In [ ]:
pd.read_csv(r"C:\Users\klemp\Desktop\savitri56\datasets\ETH_1h.csv")

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 7 columns]

In [ ]:
stock_df=pd.read_csv(r"C:\Users\klemp\Desktop\savitri56\datasets\ETH_1h.csv")

In [ ]:
stock_df

                   Date  Symbol     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  120.17  124.08  4461424.71
...                 ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  272.10  275.01   679358.87

[23674 rows x 5 columns]

top 5 rows

In [ ]:
stock_df.head()

               Date  Symbol     Low   Close      Volume
0  2020-03-13 08-PM  ETHUSD  126.87  128.71  1940673.93
1  2020-03-13 07-PM  ETHUSD  117.10  129.94  7579741.09
2  2020-03-13 06-PM  ETHUSD  115.50  119.51  4898735.81
3  2020-03-13 05-PM  ETHUSD  121.63  124.47  2753450.92
4  2020-03-13 04-PM  ETHUSD  120.17  124.08  4461424.71

top 10 rows

In [ ]:
stock_df.head(10)

               Date  Symbol     Low   Close      Volume
0  2020-03-13 08-PM  ETHUSD  126.87  128.71  1940673.93
1  2020-03-13 07-PM  ETHUSD  117.10  129.94  7579741.09
2  2020-03-13 06-PM  ETHUSD  115.50  119.51  4898735.81
3  2020-03-13 05-PM  ETHUSD  121.63  124.47  2753450.92
4  2020-03-13 04-PM  ETHUSD  120.17  124.08  4461424.71
5  2020-03-13 03-PM  ETHUSD  116.06  124.85  7378976.00
6  2020-03-13 02-PM  ETHUSD  125.50  128.39  3733916.89
7  2020-03-13 01-PM  ETHUSD  128.99  134.03  9582732.93
8  2020-03-13 12-PM  ETHUSD  126.95  131.35  3906590.52
9  2020-03-13 11-AM  ETHUSD  126.01  128.93  3311080.29

bottom 5 rows

In [ ]:
stock_df.tail()

                   Date  Symbol    Low   Close      Volume
23669  2017-07-01 03-PM  ETHUSD  265.0  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  265.0  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  265.0  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  271.0  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  272.1  275.01   679358.87

## Number of rows in dataframe

In [ ]:
len(stock_df)

23674

Access column names of dataframe

In [ ]:
stock_df.columns

Index(['Date', 'Symbol', 'Low', 'Close', 'Volume'], dtype='object')

## Accessing a columnin a dataframe

In [ ]:
stock_df.columns

Index(['Date', 'Symbol', 'Low', 'Close', 'Volume'], dtype='object')

In [ ]:
stock_df['Date']

0        2020-03-13 08-PM
1        2020-03-13 07-PM
2        2020-03-13 06-PM
3        2020-03-13 05-PM
4        2020-03-13 04-PM
               ...
23669    2017-07-01 03-PM
23670    2017-07-01 02-PM
23671    2017-07-01 01-PM
23672    2017-07-01 12-PM
23673    2017-07-01 11-AM
Name: Date, Length: 23674, dtype: object

In [ ]:
stock_df['Close']

0        128.71
1        129.94
2        119.51
3        124.47
4        124.08
          ...
23669    272.57
23670    265.74
23671    268.79
23672    274.83
23673    275.01
Name: Close, Length: 23674, dtype: float64

## Accessing multiple column in a dataframe

In [ ]:
stock_df[['Date','Close','Volume']]

                   Date   Close      Volume
0      2020-03-13 08-PM  128.71  1940673.93
1      2020-03-13 07-PM  129.94  7579741.09
2      2020-03-13 06-PM  119.51  4898735.81
3      2020-03-13 05-PM  124.47  2753450.92
4      2020-03-13 04-PM  124.08  4461424.71
...                 ...     ...         ...
23669  2017-07-01 03-PM  272.57  1500282.55
23670  2017-07-01 02-PM  265.74  1702536.85
23671  2017-07-01 01-PM  268.79  3010787.99
23672  2017-07-01 12-PM  274.83   824362.87
23673  2017-07-01 11-AM  275.01   679358.87

[23674 rows x 3 columns]

### Accessing rows and dataframe

In [ ]:
stock_df.index

RangeIndex(start=0, stop=23674, step=1)

In [ ]:
l=[1,2,3,4]

In [ ]:
l

[1, 2, 3, 4]

In [ ]:
l=[1,2,3,4,'hello',True]

In [ ]:
l

[1, 2, 3, 4, 'hello', True]

## Accessing rows

loc-labal location

df[[row,col]

In [ ]:
stock_df.loc[23672,['Date','Close']]

Date     2017-07-01 12-PM
Close              274.83
Name: 23672, dtype: object

In [ ]:
l = [1,2,3,4]
l[1:4]      #slicing a list

[2, 3, 4]

In [ ]:
d2 = [[1,2,3],
      [4,5,6],
      [7,8,9]
]
d2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
d2[2][2]

9

### slicing in loc (labeled location)

df.loc['row_label_1':'row_label_3','column_label_1':'column_label_2]

In [ ]:
stock_df.loc[23672,'Date':'Close']

Date      2017-07-01 12-PM
Symbol              ETHUSD
Low                  271.0
Close               274.83
Name: 23672, dtype: object

iloc - index based location,when we dont know labels for rows and column

In [ ]:
stock_df

                   Date  Symbol     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  120.17  124.08  4461424.71
...                 ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  272.10  275.01   679358.87

[23674 rows x 5 columns]

In [ ]:
stock_df.iloc[1,2] # row index and column index

np.float64(117.1)

In [ ]:
stock_df.iloc[1]

Date      2020-03-13 07-PM
Symbol              ETHUSD
Low                  117.1
Close               129.94
Volume          7579741.09
Name: 1, dtype: object

In [ ]:
stock_df.iloc[2,2:6]# slicing of columns using iloc

Low            115.5
Close         119.51
Volume    4898735.81
Name: 2, dtype: object

In [ ]:
stock_df.iloc[3,[2,4]]# multiple column index

Low           121.63
Volume    2753450.92
Name: 3, dtype: object

In [ ]:
stock_df.iloc[2:5,2:6]

      Low   Close      Volume
2  115.50  119.51  4898735.81
3  121.63  124.47  2753450.92
4  120.17  124.08  4461424.71

In [ ]:
stock_df.iloc[1:6,2:6]

      Low   Close      Volume
1  117.10  129.94  7579741.09
2  115.50  119.51  4898735.81
3  121.63  124.47  2753450.92
4  120.17  124.08  4461424.71
5  116.06  124.85  7378976.00

filtering

In [ ]:
stock_df

                   Date  Symbol     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  120.17  124.08  4461424.71
...                 ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  272.10  275.01   679358.87

[23674 rows x 5 columns]

In [ ]:
stock_df['Low']

0        126.87
1        117.10
2        115.50
3        121.63
4        120.17
          ...
23669    265.00
23670    265.00
23671    265.00
23672    271.00
23673    272.10
Name: Low, Length: 23674, dtype: float64

In [ ]:
stock_df['Low'] > 130

0        False
1        False
2        False
3        False
4        False
         ...
23669     True
23670     True
23671     True
23672     True
23673     True
Name: Low, Length: 23674, dtype: bool

In [ ]:
f1 = stock_df['Low'] > 130

stock_df[f1]

                   Date  Symbol     Low   Close      Volume
25     2020-03-12 07-PM  ETHUSD  136.43  138.00  3815314.09
26     2020-03-12 06-PM  ETHUSD  136.52  137.04  2516644.89
27     2020-03-12 05-PM  ETHUSD  138.32  141.80  5055228.41
28     2020-03-12 04-PM  ETHUSD  134.53  139.25  4068304.19
29     2020-03-12 03-PM  ETHUSD  137.50  141.24  3419213.89
...                 ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  272.10  275.01   679358.87

[21486 rows x 5 columns]

In [ ]:
f1 = stock_df['Low']>130

stock_gt_130=stock_df[f1]

In [ ]:
stock_gt_130.reset_index(drop = True, inplace = True)

## Adding new column

In [ ]:
stock_df.index

RangeIndex(start=0, stop=23674, step=1)

In [ ]:
len(stock_df)

23674

In [ ]:
stock_df['Random_col'] = list(range(1,len(stock_df)+1))

In [ ]:
stock_df

                   Date  Symbol     Low   Close      Volume  Random_col
0      2020-03-13 08-PM  ETHUSD  126.87  128.71  1940673.93           1
1      2020-03-13 07-PM  ETHUSD  117.10  129.94  7579741.09           2
2      2020-03-13 06-PM  ETHUSD  115.50  119.51  4898735.81           3
3      2020-03-13 05-PM  ETHUSD  121.63  124.47  2753450.92           4
4      2020-03-13 04-PM  ETHUSD  120.17  124.08  4461424.71           5
...                 ...     ...     ...     ...         ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.00  272.57  1500282.55       23670
23670  2017-07-01 02-PM  ETHUSD  265.00  265.74  1702536.85       23671
23671  2017-07-01 01-PM  ETHUSD  265.00  268.79  3010787.99       23672
23672  2017-07-01 12-PM  ETHUSD  271.00  274.83   824362.87       23673
23673  2017-07-01 11-AM  ETHUSD  272.10  275.01   679358.87       23674

[23674 rows x 6 columns]

In [ ]:
stock_df['Random_col']

0            1
1            2
2            3
3            4
4            5
         ...
23669    23670
23670    23671
23671    23672
23672    23673
23673    23674
Name: Random_col, Length: 23674, dtype: int64

Dropping column

In [ ]:
stock_df.drop(columns = ['Random_col'],inplace = True)

In [ ]:
stock_df

                   Date  Symbol     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  120.17  124.08  4461424.71
...                 ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  272.10  275.01   679358.87

[23674 rows x 5 columns]

In [244]:
stock_df.drop(columns = ['Low'],inplace = True)

In [245]:
stock_df

                   Date  Symbol   Close      Volume
0      2020-03-13 08-PM  ETHUSD  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.08  4461424.71
...                 ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  275.01   679358.87

[23674 rows x 4 columns]

In [251]:
stock_df.iloc[len(stock_df)-1]

Date      2017-07-01 11-AM
Symbol              ETHUSD
Close               275.01
Volume           679358.87
Name: 23673, dtype: object